language: go

go:
  - 1.17.x

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=coverage.out -v `go list ./... | grep -v ./example` -integration
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $GOVERALLS
