name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Goveralls Install
        run: go get golang.org/x/tools/cmd/cover && go get github.com/mattn/goveralls

      - name: Test
        run: go test -covermode=count -coverprofile=coverage.out -v `go list ./... | grep -v ./example` -integration

      - name: Goveralls
        run: goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ${{ secrets.GOVERALLS }}
